-- Persistent Scanner Intelligence state for redeploy-safe Telegram UX.
-- Safe to run repeatedly.

create table if not exists public.scanner_runtime_state (
    state_key text primary key,
    payload jsonb not null default '{}'::jsonb,
    last_success_at timestamptz,
    updated_at timestamptz not null default now()
);

create table if not exists public.scanner_scan_history (
    id bigint generated by default as identity primary key,
    run_time_utc timestamptz not null,
    rows_analyzed integer not null default 0,
    signals_count integer not null default 0,
    payload jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create index if not exists scanner_scan_history_time_idx
    on public.scanner_scan_history(run_time_utc desc);

alter table public.scanner_runtime_state enable row level security;
alter table public.scanner_scan_history enable row level security;

-- No anon/authenticated policies are created intentionally.
-- The server bot uses SUPABASE_SERVICE_KEY and can bypass RLS.

comment on table public.scanner_runtime_state is
'Last successful scanner snapshot, persisted across Railway/Render/VPS redeploys.';
comment on table public.scanner_scan_history is
'Scanner Intelligence history used for 24h funnel statistics across redeploys.';

notify pgrst, 'reload schema';
