-- Runtime strategy settings controlled by the Telegram admin bot.
-- Safe to run repeatedly.

create table if not exists public.strategy_settings (
    key text primary key,
    value text not null,
    value_type text not null check (value_type in ('bool','int','float','str')),
    category text not null,
    title text not null,
    description text not null default '',
    min_value double precision,
    max_value double precision,
    is_editable boolean not null default true,
    updated_at timestamptz not null default now(),
    updated_by text
);

create table if not exists public.strategy_settings_history (
    id bigint generated by default as identity primary key,
    setting_key text not null,
    old_value text,
    new_value text not null,
    changed_by text,
    changed_at timestamptz not null default now()
);

create index if not exists strategy_settings_category_idx
    on public.strategy_settings(category);
create index if not exists strategy_settings_history_key_time_idx
    on public.strategy_settings_history(setting_key, changed_at desc);

alter table public.strategy_settings enable row level security;
alter table public.strategy_settings_history enable row level security;

-- No anon/authenticated policies are intentionally created. The server-side bot
-- uses SUPABASE_SERVICE_KEY and can bypass RLS. Settings remain unavailable to
-- public clients.

comment on table public.strategy_settings is
'Runtime bot strategy parameters. Values here override Render ENV after startup.';
comment on table public.strategy_settings_history is
'Audit history of strategy parameter changes from Telegram or server tools.';

notify pgrst, 'reload schema';
