create table if not exists public.strategy_scan_runs (
  id bigint generated by default as identity primary key,
  strategy text not null,
  summary jsonb not null default '{}'::jsonb,
  candidates jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists strategy_scan_runs_strategy_created_idx
  on public.strategy_scan_runs(strategy, created_at desc);

create table if not exists public.strategy_setups (
  id bigint generated by default as identity primary key,
  strategy text not null,
  fingerprint text not null unique,
  symbol text not null,
  direction text not null default 'LONG',
  state text not null default 'waiting_entry',
  entry_price double precision not null,
  entry_zone_low double precision,
  entry_zone_high double precision,
  stop_price double precision not null,
  tp_price double precision not null,
  rr double precision,
  score double precision,
  d1_low double precision,
  d1_high double precision,
  fib_05 double precision,
  support_low double precision,
  support_high double precision,
  market_price double precision,
  payload jsonb not null default '{}'::jsonb,
  entered_at timestamptz,
  resolved_at timestamptz,
  outcome text,
  return_pct double precision,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists strategy_setups_strategy_state_idx
  on public.strategy_setups(strategy, state, created_at desc);

alter table public.strategy_scan_runs enable row level security;
alter table public.strategy_setups enable row level security;
