-- Run once in Supabase SQL Editor. Safe to run repeatedly.
create table if not exists public.model_registry (
  id bigint generated by default as identity primary key,
  model_version text not null unique,
  status text not null,
  config jsonb not null default '{}'::jsonb,
  metrics jsonb not null default '{}'::jsonb,
  samples_count integer not null default 0,
  is_active boolean not null default false,
  created_at timestamptz not null default now(),
  activated_at timestamptz
);
create index if not exists model_registry_active_idx on public.model_registry(is_active, created_at desc);

create table if not exists public.training_runs (
  id bigint generated by default as identity primary key,
  model_version text not null,
  metrics jsonb not null default '{}'::jsonb,
  feature_importance jsonb not null default '{}'::jsonb,
  samples_count integer not null default 0,
  status text not null,
  summary jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists training_runs_created_idx on public.training_runs(created_at desc);

-- Service-role writes bypass RLS. Keep tables protected from anonymous clients.
alter table public.model_registry enable row level security;
alter table public.training_runs enable row level security;
