-- AI Optimizer v17 + Adaptive Models v18. Safe to run repeatedly.
create extension if not exists pgcrypto;

create table if not exists public.ai_optimizer_runs (
    id uuid primary key default gen_random_uuid(),
    status text not null,
    trigger text,
    samples integer not null default 0,
    baseline jsonb not null default '{}'::jsonb,
    recommendations_count integer not null default 0,
    created_at timestamptz not null default now()
);

create table if not exists public.ai_optimizer_recommendations (
    id uuid primary key default gen_random_uuid(),
    run_id uuid references public.ai_optimizer_runs(id) on delete set null,
    kind text not null,
    setting_key text,
    symbol text,
    current_value text,
    proposed_value text,
    reason text,
    metrics jsonb not null default '{}'::jsonb,
    status text not null default 'pending' check (status in ('pending','applied','rejected')),
    applied_at timestamptz,
    applied_by text,
    created_at timestamptz not null default now()
);

create index if not exists ai_optimizer_recommendations_status_idx on public.ai_optimizer_recommendations(status, created_at desc);

create table if not exists public.adaptive_model_versions (
    id uuid primary key default gen_random_uuid(),
    version text not null unique,
    status text not null check (status in ('candidate','champion','archived','rejected')),
    algorithm text not null,
    samples_train integer not null default 0,
    samples_validation integer not null default 0,
    metrics jsonb not null default '{}'::jsonb,
    model_json jsonb not null default '{}'::jsonb,
    trigger text,
    created_at timestamptz not null default now(),
    activated_at timestamptz
);

create index if not exists adaptive_model_versions_status_idx on public.adaptive_model_versions(status, created_at desc);

alter table public.ai_optimizer_runs enable row level security;
alter table public.ai_optimizer_recommendations enable row level security;
alter table public.adaptive_model_versions enable row level security;

comment on table public.ai_optimizer_runs is 'Nightly Paper Trading optimization analyses.';
comment on table public.ai_optimizer_recommendations is 'Human-approved strategy recommendations generated by AI Optimizer.';
comment on table public.adaptive_model_versions is 'Versioned lightweight probability models trained on chronological Paper outcomes.';
notify pgrst, 'reload schema';
